samples/clients/csharp-wpf/VoiceAssistantClient/MainWindow.xaml.cs
Partners have requested information about how to implement "barge in;" more specifically, ensuring that a new interaction (e.g. via a keyword) can interrupt an ongoing existing interaction. This is a pretty simple thing to achieve and a decent default behavior, so it should be reflected in the Voice Assistant client.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
* Trigger a longer response from a bot, e.g. a long utterance to an echo bot
* During playback, press the mic icon or say a keyword
* Observe that the ongoing playback stops as listening begins for the next interaction
=> Cancel ongoing audio output upon session start (button press, KWS)

samples/clients/csharp-wpf/VoiceAssistantClient/MainWindow.xaml.cs
There's a specific error that the service produces when a timeout gracefully disconnects via timeout (standard: 5 minutes). We currently present this error just like any other one, but that's causing a common misperception that something is wrong. This isn't an exceptional condition and so we shouldn't present it as such. The fix just suppresses the big red bubble and keeps a more useful explanation in the status box at the bottom of hte tool.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
Run the code. Connect to a bot or Custom Commands application. Let the …
=> Suppress error dialogs generated in response to graceful timeouts

samples/clients/csharp-wpf/README.md, samples/clients/csharp-wpf/VoiceAssistantClient/MainWindow.xaml.cs
Per previous change from Travis, we no longer display the connection timeout cancellation event as a red-text error bubble in the main dialog window. Therefore updating the tool's README to describe the new behavior. Also give some more details as comment in the source code.
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ ] Feature
```
=> Update doc for Windows Voice Assistant Client to address connection timeout

clients/csharp-wpf/VoiceAssistantClient/MainWindow.xaml.cs, clients/csharp-wpf/VoiceAssistantClient/Settings/ConnectionProfile.cs, clients/csharp-wpf/VoiceAssistantClient/Settings/RuntimeSettings.cs, clients/csharp-wpf/VoiceAssistantClient/SettingsDialog.xaml, clients/csharp-wpf/VoiceAssistantClient/SettingsDialog.xaml.cs
* BotFrameworkConfig.FromSubscription() contains a parameter called BotId. This PR enables setting a Bot Handle along with the Subscription Key and Subscription Region.
[ ] Yes
[x] No
[ ] Bugfix
[x] Feature
*  Add Subscription Key, Subscription Region, and BotId to a Connection Profile to connect
=> Add support for BotId

clients/csharp-wpf/JsonViewControl/JsonViewControl.csproj, clients/csharp-wpf/JsonViewControl/packages.config, clients/csharp-wpf/VoiceAssistantClient/App.config, clients/csharp-wpf/VoiceAssistantClient/Properties/AssemblyInfo.cs, clients/csharp-wpf/VoiceAssistantClient/Settings/AppSettings.cs, clients/csharp-wpf/VoiceAssistantClient/Settings/ConnectionProfile.cs, clients/csharp-wpf/VoiceAssistantClient/Settings/RuntimeSettings.cs, clients/csharp-wpf/VoiceAssistantClient/SettingsDialog.xaml, clients/csharp-wpf/VoiceAssistantClient/SettingsDialog.xaml.cs, clients/csharp-wpf/VoiceAssistantClient/VoiceAssistantClient.csproj, clients/csharp-wpf/VoiceAssistantClient/packages.config
* Previously the app was losing scope when deactivated (switching to another app) - text fields were reverting back to the original text from previous profile. This fix is to ensure that the values entered in the respective fields are not lost when application is deactivated. 
* Combo boxes with previous history of Subscription Key, Region, and Custom Commands App Id have been replaced with Text Boxes.
* Delete Profile button has been added to remove a profile and its associated values from app history. 
[ ] Yes
[x] No
```
[x] Bugfix
[x] Feature
```
*  Create a new …
=> Fix for App losing scope and Delete Profile button

azure-pipelines.yml
* Update artifact names, including adding build number, since I am about to post some of them as GitHub releases
* Update display names for build tasks so they align nicely in the build log
* Add build task for UWP Voice Assistant Sample. Disabled until private build agent issues are fixed.
=> Update artifact names. Also prep for building UWP Voice Assistant Sample (not yet enabled)

clients/csharp-wpf/README.md, clients/csharp-wpf/VoiceAssistantClient/MainWindow.xaml.cs, clients/csharp-wpf/VoiceAssistantClient/SettingsDialog.xaml, clients/csharp-wpf/VoiceAssistantClient/SettingsDialog.xaml.cs
* This PR address multiple issues
* On discard changes, modified profile settings persisted on next activation. *Fix* - modification to a profile's settings will not stay in focus. A profiles saved values will be used if changes are discarded. 
* FromId, and LanguageId were not mapped correctly.
* Settings Dialog opened at random positions - *Fix*: now opens at the center of the main window
* If all profiles are deleted, the last deleted profile name was persisting on next application launch - *Fix* : If all profiles are deleted, ConnectionProfileComboBox.Text will be empty
* UpdateState was now being called when ConnectionProfileComboBox Text changed. This prevented the indication that a profile name is required to proceed- *Fix*: If profile name is empty red textblock will show …
=> Fix for persistent values on discard changes

clients/csharp-wpf/VoiceAssistantClient/SettingsDialog.xaml.cs
* Saved profile's settings were not shown on Settings Dialog Activation when unsaved profile was discarded. 
* If all profiles are deleted, the last profile's name lingered in the ConnectionProfileComboBox
* Fixed the above two issues.
[ ] Yes
[x] No
[x] Bugfix
[ ] Feature
1. Create Profile 1
2. Enter 111 for Subscription Key and Region
3. Save Profile
4. Open the Settings Dialog and enter Profile 2 in the Connection Profile dropdown
5. Discard Changes
6. Open the Settings Dialog - Profile 1 and its associated value should be seen
7. Repeat steps 1 - 3 with different …
=> Discard unsaved profile

azure-pipelines.yml
* Add UWP Voice Assistant sample to the Azure DevOps build pipeline
* Use a self-hosted build agent instead of Microsoft hosted agent. This allows us to run the builds on our pre-release versions of Windows needed for the UWP sample.
* I had to disable the Notice ADO task for now, since it fails to run on my local machine. I have an e-mail out to support team to see what I can do to fix this
* Additional minor change in the UWP Sample app to remove links to non-existing documents
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ ] Feature
[x ] Other... Please describe:
```
Update build pipeline
=> Switch to using self-hosted build agent on Windows Insiders machine, and add UWP sample to the build

clients/cpp-console/GGECSpeaker.md, clients/cpp-console/RaspberryPi.md, clients/cpp-console/scripts/GGEC/deployGGEC.bat, clients/csharp-uwp/UWPVoiceAssistantSample.sln, clients/csharp-uwp/UWPVoiceAssistantSample/App.xaml.cs, clients/csharp-uwp/UWPVoiceAssistantSample/MVAKeywords/contosoInfo.txt, clients/csharp-uwp/UWPVoiceAssistantSample/SDKKeywords/contosoInfo.txt, clients/csharp-uwp/UWPVoiceAssistantSample/UWPVoiceAssistantSample.csproj, keyword-models/README.md
Both C++ client and UWP sample app had their own .table files. We would like to save them in one place and manage version control there. They will be replaced soon with better one from the KWS team.
With this change, all .table files are moved to a new folder in the root of the repo called keyword_models.
I have not verified the change to the LINUX script, since I don't have a RPI.
I compiled the UWP sample app, and I see that after my change there is a folder and file named SDKKeywords\contoso.table in the output folder (e.g. \bin\x64\Debug\), just like before.
Also, when I debug the app via VS, it creates an AppX folder, and I see the SDKKeywords\contoso.table file there as well. Both indicate that the file is copied correctly just like before my change.
To preserve the view of the …
=> Consolidate all Speech SDK KWS in one folder

clients/cpp-console/src/common/mainAudio.cpp
* Fix bug #255 - do not turn on KWS after TTS playback is done, if the user has previously selected to stop TTS
* This state machine will also help us easily implement optional barge-in when a configuration settings in the JSON indicates that barge-in needs to be supported (if the device has good echo cancellation). This is logged as feature request #262.
If the process I found out that if we are loading a wrong binary files as the KWS table, no error is generated. Logged as bug #264.
```
[ ] Yes
[x ] No
```
```
[x ] Bugfix
[ ] Feature
```
* Tested by selecting …
=> Fix bug #255 by defining a state machine for KWS activation

clients/cpp-console/configs/config.json, clients/cpp-console/include/AgentConfiguration.h, clients/cpp-console/src/GGEC/GGECDeviceStatusIndicators.cpp, clients/cpp-console/src/GGEC/GGECLinuxAudioPlayer.cpp, clients/cpp-console/src/common/AgentConfiguration.cpp, clients/cpp-console/src/common/mainAudio.cpp
Barge in support can now be triggered by the configuration file.
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[x ] Feature
[ x] Refactoring (no functional changes, no api changes)
```
Try to barge in with the setting as false/true.
=> Add Barge in as configurable option

clients/cpp-console/src/linux/LinuxAudioPlayer.cpp
There was a crash happening when we tried to reopen the audio player sometimes
Closes #374 
```
[ ] Yes
[x ] No
```
```
[x ] Bugfix
[ ] Feature
```
build and run on Raspberry pi for a few minutes back and forth audio. See that it doesn't crash
=> added close to the handle on stop.

clients/csharp-uwp/UWPVoiceAssistantSample/KeywordRegistration.cs
* Small fix for a regression in ActivationSignalDetectionConfiguration retrieval that caused background activations to fail when disabling the configuration during launch (before audio retrieval)
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
* Before: background activation won't work, failing with a cryptic HRESULT during audio initialization with CreateAudioInputNodeAsync
* After: background activation works again
=> Fix background activation with existing MVA keyword configuration retrieval

clients/csharp-wpf/JsonViewControl/JsonViewControl.csproj, clients/csharp-wpf/JsonViewControl/app.config, clients/csharp-wpf/JsonViewControl/packages.config, clients/csharp-wpf/VoiceAssistantClient/Properties/AssemblyInfo.cs, clients/csharp-wpf/VoiceAssistantClient/SettingsDialog.xaml.cs, clients/csharp-wpf/VoiceAssistantClient/VoiceAssistantClient.csproj, clients/csharp-wpf/VoiceAssistantClient/packages.config
Update all Nugets to latest version (except Jot). This includes Speech SDK 1.12. 
Update WVAC app version to 1.12
I'm in the process of testing this change. Submitting a PR to trigger the official build. I will test the artifact package that eventualy will be hosted in the Releases tab.
Update: Manual tests pass, with and without keyword activation
```
[ ] Yes
[ x] No
```
```
[ ] Bugfix
[ ] Feature
[x ] Other... Please describe:
Nuget update
=> Update Windows Voice Assistant Client to Speech SDK 1.12

clients/csharp-dotnet-core/voice-assistant-test/README.md, clients/csharp-dotnet-core/voice-assistant-test/docs/GETTING-STARTED-GUIDE.md, clients/csharp-dotnet-core/voice-assistant-test/tool/BotConnector.cs, clients/csharp-dotnet-core/voice-assistant-test/tool/VoiceAssistantTest.csproj, custom-commands/hospitality/test/hospitality_skill.json
* Update all Nugets (including update to Speech SDK 1.12)
* Update doc on UPL measurement
* Fix names of JSON keys related to UPL
* Use the typo-free version of the Speech property SPEECH-TransmitLengthBeforThrottleMs (both should work now, as confirmed when looking at Speech SDK code)
* Update JSON key names to the agreed names to match the previous code changes
* Use a more compact style for the Hospitality test JSON, and add "Skip" fields since we constantly need them when investigating test failures.
Some Hospitality tests are failing due to timeout in the 2nd turn (unrelated to the above changes). Also some UPL numbers are wrong. Will investigate both and fix in a separate  PR.
=> Updates to Voice Assistant Test Tool

clients/csharp-dotnet-core/voice-assistant-test/tool/BotConnector.cs, clients/csharp-dotnet-core/voice-assistant-test/tool/DialogResult.cs, clients/csharp-dotnet-core/voice-assistant-test/tool/MainService.cs, custom-commands/hospitality/test/hospitality_skill.json, custom-commands/hospitality/test/input-files/Test_AdjustTemperature_TextInput.json, custom-commands/hospitality/test/input-files/Test_AdjustTemperature_VoiceInput.json, custom-commands/hospitality/test/input-files/Test_FallbackCommand_TextInput.json, custom-commands/hospitality/test/input-files/Test_FallbackCommand_VoiceInput.json, custom-commands/hospitality/test/input-files/Test_Greeting_TextInput.json, custom-commands/hospitality/test/input-files/Test_Greeting_VoiceInput.json, custom-commands/hospitality/test/input-files/Test_Help_TextInput.json, custom-commands/hospitality/test/input-files/Test_Help_VoiceInput.json, custom-commands/hospitality/test/input-files/Test_OpenClose_TextInput.json, custom-commands/hospitality/test/input-files/Test_OpenClose_VoiceInput.json, custom-commands/hospitality/test/input-files/Test_TurnOnOff_TextInput.json, custom-commands/hospitality/test/input-files/Test_TurnOnOff_VoiceInput.json
* There was a duplication of "Latency" values stored in BotReply objects and a separate UPL values which the BotConnector returns. Unify them and only calculate and report UPL.
* Update test configuration to use the expected UPL instead of just expected latency
* Simplify how the stopwatch is managed. No need to start/stop so many times. Restart once on SettionStrart, and then read elapsed time when an activity is received. 
Hospitality WAV tests are failing, unrelated to the above changes, because for some reason it takes 4-5 seconds to get a reply in the test, even though when I do the same thing manually using Windows Voice Assistant Client everything runs fast. I'll file a bug on it.
Also, we need to wait and get elapsed time when the first TTS audio buffer is received, not when the …
=> Fix & simplify UPL calculating in Voice Assistant Test

clients/csharp-uwp/README.md, clients/csharp-uwp/UWPVoiceAssistantSample/KeywordRegistration.cs
* An existing keyword configuration was not enabled because its model data was not set. This issue was raised when another MVA app was registered and uninstalled. The keyword from the initial MVA App remained disabled after enabling Voice Activation. 
* In this PR, the existing configuration is retrieved, its model data is set, and it is enabled.
[ ] Yes
[x] No
[x] Bugfix
[ ] Feature
* Install the UWP Voice Assistant Sample (MVA App 1) Voice Activate
* Install another MVA App (MVA App 2), disable Voice Activation for MVA App 1
* Voice Activate MVA App 2.
* Uninstall …
=> Fix existing keyword configuration

custom-commands/scripts/deployAll.ps1, custom-commands/scripts/deployCustomCommands.ps1
Updated deployment script to only use new model. Fixed typo in main script
Closes #428 
```
[ ] Yes
[ ] No
```
```
[ x] Bugfix
[ ] Feature
```
deploy a demo and check the custom keywords
=> Fixed Custom Keywords in deployment script

clients/cpp-console/scripts/linux/buildArmLinux.sh
* This introduces a generic Build script for Linux ARM and closes #451 
* However it needs some discussion on the documentation and impact on other scripts, eg the service and MAS. How do we manage the docs for device specific information, and generic Linux information. For instance on Jetson board I basically followed the "RaspberryPi" doc, do we rename it?
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
Test on Raspberry Pi with Ubuntu ARM32
Test on NVidia Jetson with Ubuntu ARM64
* Ensure it …
=> Add LinuxARM script

clients/csharp-wpf/VoiceAssistantClient/Properties/AssemblyInfo.cs, clients/csharp-wpf/VoiceAssistantClient/VoiceAssistantClient.csproj, clients/csharp-wpf/VoiceAssistantClient/packages.config
Speech SDK 1.12 crashes when an error is sent from Direct Line Speech. Until the fix is made public, downgrade this tool to use Speech SDK 1.11
```
[ ] Yes
[x ] No
```
```
[x ] Bugfix
[ ] Feature
```
=> Downgrade to SpeechSDK 1.11 due to bug in 1.12 & 12.1

clients/csharp-wpf/VoiceAssistantClient/SettingsDialog.xaml
* The settings buttons are not working (e.g. "save and apply profile")
* This is a regression as a result of the "GitHub" link that was added to the settings page
The fix is to limit the size of the "GitHub" text box. By default it covers the whole row and masks the buttons, as Chris pointed out (Thanks Chris!)
```
[ ] Yes
[x ] No
```
```
[x ] Bugfix
[ ] Feature
```
=> Fix regression in Windows Voice Assistant Client

NOTICE.txt, clients/csharp-wpf/VoiceAssistantClient/App.config, clients/csharp-wpf/VoiceAssistantClient/MainWindow.xaml.cs, clients/csharp-wpf/VoiceAssistantClient/VoiceAssistantClient.csproj, clients/csharp-wpf/VoiceAssistantClient/packages.config
Since it does not have an Open Source license that we can use under our MIT license.
Based on [this document](https://docs.microsoft.com/en-us/adaptive-cards/sdk/rendering-cards/net-wpf/getting-started), I'm positive this is the right change to remove dependency but still have some Adaptive Cards display.
```
[x ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
[x ] Other... Please describe:
Limit the function of adaptive cards. But I'm not sure yet how.
I made sure there is no regression in Custom Commands applications (which do not use Adaptive Cards).
I have not tested with bots that return Adaptive …
```
=> Remove dependency on NuGet Extended.Wpf.Toolkit

azure-pipelines.yml
This is just a try to see if the UWP app will compile. I'm hoping MS self-hosted build agents were already updated to support latest Win10 release, so we don't have to keep running our own laptops as build machines.
=> Trying this out: switch back to using MS hosted build agents

clients/README.md, clients/cpp-console/configs/config.json, clients/cpp-console/docs/Windows.md, clients/cpp-console/include/AgentConfiguration.h, clients/cpp-console/src/common/AgentConfiguration.cpp
Expose the SRLanguage config param in the C++ sample. It's already supported in the Windows Voice Assistant Client.
Tested against a de-de Custom Command application on Windows. I have not yet tested on RPi4.
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[x ] Feature
```
=> Add language support to c++ sample

custom-commands/demos/automotive/skill/en-us/AutomotiveDemo.json, custom-commands/demos/careroom/skill/en-us/CareRoomDemo.json, custom-commands/demos/hospitality/skill/en-us/HospitalityDemo.json, custom-commands/demos/inventory/skill/en-us/InventoryDemo.json, custom-commands/demos/scripts/deployAll.ps1, custom-commands/demos/scripts/deployCustomCommands.ps1
Pass language/culture as HTTP header in Azure function call, so the Azure function can reply with the correct language. The change in the Azure function will be in a separate PR.
Also clean up variable names in the script and remove duplicates.
```
[ ] Yes
[x] No
```
=> Pass language/calture as HTTP header in Azure function call

custom-commands/demos/README.md, custom-commands/demos/scripts/azuredeploy.json, custom-commands/demos/scripts/azuredeploy.parameters.json, custom-commands/demos/scripts/deployAll.ps1, custom-commands/demos/scripts/deployCustomCommands.ps1, custom-commands/demos/scripts/deployTemplate.ps1
* The first REST call in the deployCustomCommands.ps1 script was still using a preview version of the Custom Command web API. Switch to using 1.0 API. 
* The switch to 1.0 API meant that we no longer send the LUIS prediction and authoring keys. We now send a token replacement instead.
* The first REST call in deployCustomCommands.ps1 now both creates a new Custom Command project and provisions it with the JSON model of the project. Previously this was done by two separate calls
* Update parameter names in the scripts. In particular, make it clear what is a LUIS runtime (aka prediction) and what is LUIS authoring Azure resource. Remove the word "key" when it was not really pointing to a secrete key, but Azure resource name
* Other cleanup and simplifications
* Update doc to reflect the …
=> Update Custom Commands deployment script

clients/csharp-dotnet-core/voice-assistant-test/README.md, clients/csharp-dotnet-core/voice-assistant-test/docs/json-templates/app-config-template.json, clients/csharp-dotnet-core/voice-assistant-test/tool/AppSettings.cs, clients/csharp-dotnet-core/voice-assistant-test/tool/BotConnector.cs, clients/csharp-dotnet-core/voice-assistant-test/tool/FilePullStreamCallback.cs, clients/csharp-dotnet-core/voice-assistant-test/tool/GlobalPullStream.cs, clients/csharp-dotnet-core/voice-assistant-test/tool/MainService.cs
This PR makes the default method of injecting wav files a "pullstream" instead of a "pushstream". This seems to work much better for large sets of tests. Push stream can now be used as an option in the config file.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
=> Changed to pullstream for SDK wav audio

clients/csharp-uwp/UWPVoiceAssistantSample/App.xaml
When Windows 10 is set to dark mode, some fonts and app colors were automatically changed making the app unreadable in some sections. This forces the app to run in Light mode independent of system settings, which is readable.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* App should always have a white background throughout, and chat bubble text in right-most panel should be black.
=> Force light theme in UWP Client App

custom-commands/demos/README.md
I tried DotNet SDK 5.0 didn't work due to custom command requires DotNet core 2.1 to build.
Refine demo readme. Explicitly requrie dot net core 2.1 as SDK.
I tried .net 5.0 SDK offline and it didn't work since the CC requires .net core 2.1 to build
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
=> Update readme for dot net version

azure-pipelines.yml
Disable signing until we find time to set up a Key Vault. The correct certificate is about to expire: "All certificates used for integrating with ESRP are now required to be held in an Azure Key Vault (AKV)"
MS internal link:
https://microsoft.sharepoint.com/teams/prss/esrp/info/ESRP%20Onboarding%20Wiki/Generating%20the%20ESRP%20Authentication%20(Request%20Signing)%20certificate.aspx
=> Disable exe signing of Windows Voice Assistant Client
