Azure-Samples/Cognitive-Services-Voice-Assistant

- samples/clients/csharp-wpf/VoiceAssistantClient/ConversationView.xaml
- samples/clients/csharp-wpf/VoiceAssistantClient/Models.cs
* Explain #92
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Collapsed bubble when text is empty

- samples/clients/csharp-wpf/README.md
documentation update
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ ] Feature
```
The code appears in the README of the wpf sample
> added example of responding to the bot to the documentation.

- samples/clients/cpp-console/RaspberryPi.md
*  fixes #114
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
*  Check RaspberryPi.md for new PuTTY link
N/A 
```
```
* Check RaspberryPi.md for new PuTTY link
> PuTTY SSH client added

- samples/clients/cpp-console/RaspberryPi.md
* Fixed #117 this is the 3rd PR to complete this issue
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
* Check that the usage is correct
> CorrectRunningTheSample

- samples/clients/cpp-console/RaspberryPi.md
* Partial fix #117 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
New build instructions actually work
> Build on ARM32

- samples/clients/cpp-console/RaspberryPi.md
* fixes #116  
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
*  Read the RPI md file
N/A
* Link to Ubuntu Install instructions
> Ubuntu Install tutorial

- samples/clients/cpp-console/RaspberryPi.md
* Partial fix #117 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
* Documentation for cloning repo and getting Speech SDK
> Setting up the code

- CODEOWNERS
* Will use this to manage who is added as PR review. Later on, if we want, we can put specific people on specific files/folders.
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ ] Feature
[ x] Other... Please describe:
Repo settings
> Add CODEOWNERS to the repo

- custom-commands/hospitality/deployment/DEPLOYREADME.md
The link was broken for some reason. Fixed now.
```
[ ] Yes
[ x] No
```
```
[x ] Bugfix
[ ] Feature
```
> fixed link in deploy button

- clients/csharp-wpf/VoiceAssistantClient/Properties/AssemblyInfo.cs
- clients/csharp-wpf/VoiceAssistantClient/VoiceAssistantClient.csproj
- clients/csharp-wpf/VoiceAssistantClient/packages.config
* ...
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
Update Microsoft.CognitiveServices.Speech from 1.9.0 to 1.10.0 for VoiceAssistantClient project.
```
cd [repo-name]
npm install
```
```
```
* ...
> Update Microsoft.CognitiveServices.Speech from 1.9.0 to 1.10.0

- clients/csharp-wpf/README.md
Workaround note for bug #150, until we find the proper fix
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ ] Feature
```
> Workaround note for bug #150

- clients/csharp-wpf/README.md
- clients/csharp-wpf/VoiceAssistantClient/VoiceAssistantClient.csproj
This is a workaround to fix Unable to load DLL Microsoft.CognitiveServices.Speech.core.dll reported in issue #150.
Besides, remove the manual workaround Note in README.md.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
> A workaround to fix Unable to load DLL Microsoft.CognitiveServices.Speech.core.dll reported in issue #150.

- clients/cpp-console/GGECSpeaker.md
* Add WiFi instructions to the speaker to fix #167 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
Check the GGEC readme in the device setup
* WiFi instructions now added
> wifi setup

- clients/cpp-console/GGECSpeaker.md
* Fix #170 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
Test building and deploying to GGEC speaker
* ...
> Updated build instructions

- clients/cpp-console/GGECSpeaker.md
* Document fix #172 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
Set up a new speaker and connect to service
If the speaker initially gives Error 2460, fix the TLS issue with the troubleshooting steps in this PR
* Speech service can be accessed after following this fix
It would be better to fix this on the users behalf in code, not as a documentation issue.
> Add help for error 2460

- clients/csharp-wpf/VoiceAssistantClient/MainWindow.xaml.cs
- clients/csharp-wpf/VoiceAssistantClient/Settings/RuntimeSettings.cs
- clients/csharp-wpf/VoiceAssistantClient/SettingsDialog.xaml.cs
* Remove unused parameters from RuntimeSettings.Set()
[ ] Yes
[x] No
[ ] Bugfix
[ ] Feature
> Remove unneeded parameters

- clients/csharp-wpf/VoiceAssistantClient/MainWindow.xaml.cs
- clients/csharp-wpf/VoiceAssistantClient/Settings/ConnectionProfile.cs
- clients/csharp-wpf/VoiceAssistantClient/Settings/RuntimeSettings.cs
- clients/csharp-wpf/VoiceAssistantClient/SettingsDialog.xaml.cs
* Bug Fix - Property from previous bot persisted in new connection profile
```
[ ] Yes
[x] No
```
[x] Bugfix
[ ] Feature
* Enter required values and connect to a Bot
* Enter the required values for another Bot - new bot connection profile will be used.
> Bug fix for previous PR

- clients/cpp-console/GGECSpeaker.md
* Fix #191 191
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
Use GGEC readme file to connect to WiFi
```
```
* ...
> Updated WiFi instructions

- clients/csharp-wpf/VoiceAssistantClient/MainWindow.xaml.cs
- clients/csharp-wpf/VoiceAssistantClient/Settings/ConnectionProfile.cs
- clients/csharp-wpf/VoiceAssistantClient/Settings/RuntimeSettings.cs
- clients/csharp-wpf/VoiceAssistantClient/SettingsDialog.xaml
- clients/csharp-wpf/VoiceAssistantClient/SettingsDialog.xaml.cs
* Reduce build warnings introduced by Bot Profile PR
[ ] Yes
[x] No
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
> reduce build warnings

- clients/csharp-dotnet-core/voice-assistant-test/docs/json-templates/test-config-template.json
Wrap ExpectedTTSAudioResponseDuration number with [].
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
> Wrap ExpectedTTSAudioResponseDuration with [].

- clients/csharp-dotnet-core/voice-assistant-test/README.md
Update Voice Assistant Tool document for new topic Testing response activities with random text and speak from a predefined set
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
> Update README.md of voice-assistant-test

- clients/csharp-wpf/VoiceAssistantClient/MainWindow.xaml.cs
- clients/csharp-wpf/VoiceAssistantClient/SettingsDialog.xaml.cs
* Selecting blank profile name allows creation of new profile
* Refactor repetitive code
[ ] Yes
[x] No
[ ] Bugfix
[x] Feature
[x] Code style update (formatting, local variables)
*  Create and save several profiles
* Delete each profile until none remain
* Create and save a new profile
* Click Reconnect
> Selecting blank profile allows creation of new profile

- clients/csharp-wpf/VoiceAssistantClient/SettingsDialog.xaml.cs
* Fix for textboxes losing when switching between applciations - introduced during blankprofile PR
[ ] Yes
[x] No
[x] Bugfix
[ ] Feature
> Textbox Scope loss

- azure-pipelines.yml
Using a new certificate for Voice Assistant sample code. We can do the same for other executables in this repo.
> Code-sign the Windows Voice Assistant Client

- clients/csharp-wpf/VoiceAssistantClient/SettingsDialog.xaml.cs
* Index 0 for blank profile was out of range. -- Fixed
* First profile was not being created correctly. 
[ ] Yes
[x] No
[x] Bugfix
[ ] Feature
> Index was out of range for blank profile

- NOTICE.txt
* Add NLog license to NOTICE.txt. UWP Sample uses it.
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ ] Feature
```
> Add NLog license to NOTICE.txt. UWP Sample uses it.

- clients/csharp-wpf/README.md
Update README of Windows Voice Assistant Client to mention the option to download an executable
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ ] Feature
```
> Update README of Windows Voice Assistant Client to mention the option to download an executable

- clients/csharp-uwp/UWPVoiceAssistantSample/AgentSessionManager.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/DialogManager.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/DirectLineSpeechDialogBackend.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/Logging/NLogProvider.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/MainPage.xaml
- clients/csharp-uwp/UWPVoiceAssistantSample/MainPage.xaml.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/SignalDetectionHelper.cs
Made logging async to speed up time to recognize
Converted Debug.Writelines to logger.Logs in DialogManager and DirectLineSpeechBackend
Added "Clear logs" button
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[x ] Feature
```
> Make logging async

- clients/cpp-console/include/AgentConfiguration.h
- clients/cpp-console/src/common/AgentConfiguration.cpp
- clients/cpp-console/src/common/mainAudio.cpp
Update code to:
1. Check for KWS file and print proper error if it does not exist.
2. Print human readable timestamp
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[x] Feature
```
```
Run the cpp-console to watch:
1. it will print proper message and exit if KWS file does not exist or its extension is not ".table".
2. it will print human readable timestamp.
```
> Update code to:

- clients/csharp-uwp/UWPVoiceAssistantSample/MainPage.xaml
- clients/csharp-uwp/UWPVoiceAssistantSample/MainPage.xaml.cs
* Added padding to chat window and application state grid.
[ ] Yes
[x] No
[x] Bugfix
[ ] Feature
> Add padding to UI

- clients/csharp-uwp/UWPVoiceAssistantSample/MainPage.xaml.cs
* Add condition to handle if microphone is disabled but VA is enabled.
* Add textwrapping in Log Window
[ ] Yes
[x] No
[x] Bugfix
[ ] Feature
> AudioStatus and Log Window UI Update

- clients/cpp-console/docs/RaspberryPi.md
- clients/cpp-console/include/AudioPlayer.h
- clients/cpp-console/include/AudioPlayerState.h
- clients/cpp-console/include/LinuxAudioPlayer.h
- clients/cpp-console/include/WindowsAudioPlayer.h
- clients/cpp-console/scripts/GGEC/deployGGEC.bat
- clients/cpp-console/src/GGEC/GGECLinuxAudioPlayer.cpp
- clients/cpp-console/src/common/mainAudio.cpp
- clients/cpp-console/src/linux/LinuxAudioPlayer.cpp
- clients/cpp-console/src/windows/WindowsAudioPlayer.cpp
refactored main functions to get ready for barge in. Added StopAllPlayback to audio players
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[x ] Feature
```
> added stop all playback function to audio players

- custom-commands/hospitality/deployment/DEPLOYREADME.md
* Simple change to accommodate for the WIP message to be displayed below for the Build demo
```
[ ] Yes
[ x] No
```
[ ] Bugfix
[ ] Feature
[ x] Documentation content changes
NA
NA
> minor change in text for build demo

- README.md
- clients/java-android/README.md
Updates to the root README.md to align with recent changes in the repo. This includes breaking down the single content table into multiple tables, as we are about to add more content.
Also connect to the Botframework-Solution GitHub repo for the Java Android sample.
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ ] Feature
```
> Documentation update

- clients/csharp-uwp/UWPVoiceAssistantSample/App.xaml.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/AppSettings.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/DialogManager.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/KeywordRegistration.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/LocalSettingsHelper.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/MainPage.xaml
- clients/csharp-uwp/UWPVoiceAssistantSample/MainPage.xaml.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/UIAudioStatus.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/UWPVoiceAssistantSample.csproj
- clients/csharp-uwp/UWPVoiceAssistantSample/config.json
- clients/csharp-uwp/UWPVoiceAssistantSampleTests/KeywordRegistrationTests.cs
- clients/csharp-uwp/UWPVoiceAssistantSampleTests/UnitTestApp.xaml.cs
* config.json allows settings path for bin and table file.
* Documentation must indicate that the values are relative to ms:appx///
* Should the Keyword Display name or any other values need to be configurable?
* csproj copies table files to the SDKKeyword Folder, should the same be done for bin files?
[ ] Yes
[x] No
[ ] Bugfix
[x] Feature
*  Uninstall existing version of the app and start application.
* Open Config and modify ms-appx to ms-app
* Load Config - an error will be thrown in logs indicating file does not start with ms-appx
> Specify KWS file path in config.json

- clients/cpp-console/scripts/GGEC/buildGGEC.bat
- clients/cpp-console/scripts/GGEC/buildGGECFromFile.bat
- clients/cpp-console/src/common/AgentConfiguration.cpp
fix the GGEC script.
```
[ ] Yes
[x ] No
```
```
[ x] Bugfix
[ ] Feature
```
setup docker and run the buildGGEC.bat script
> added filesystem to GGEC script.

- custom-commands/hospitality/deployment/README.md
* Fix broken syntax and add a cleaning up your azure resources section
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ ] Feature
```
> Fix broken syntax and add a cleaning up your azure resources section

- clients/cpp-console/docs/RaspberryPi.md
* Fix #317 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
Look at RaspberryPi.md, the Troubleshooting section
```
```
* Spelling corrected, layout fixed, duplicate removed
> Removed duplicate issue

- clients/cpp-console/README.md
- clients/cpp-console/docs/BuildForLinuxOnWindows.md
- custom-commands/hospitality/README.md
- docs/CreateSampleVoiceAssistant.md
* Copy Fan's "compiling for Linux on a Windows machine" wiki and put it as a linked file in the repo. it will get better visiblity that way. I did not make changes to Fan's text, just copied it.
* Other small doc updates
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
>
> Some document updates

- custom-commands/hospitality/deployment/README.md
Give the users a more in depth breakdown of the individual steps of the deployment.
```
[] Yes
[x] No
```
Closes #337
> Updated with greater detail on what we do.

- docs/CreateSampleVoiceAssistant.md
* ...
Close #365 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
Check link on VA
* ...
> Add VA link to CC sample instructions

- clients/csharp-uwp/UWPVoiceAssistantSample/AgentSessionManager.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/App.xaml.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/AudioInput/AgentAudioInputProvider.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/DialogManager.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/Logging/NLogProvider.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/MainPage.xaml.cs
Fixes an issue where the log index was off because there are multiple instances of loggers sharing the same queue but not the same index.
```
[ ] Yes
[ x] No
```
```
[x ] Bugfix
[ ] Feature
```
Logs should print in order in the file and in the UI
The class the logs come from (output file only), the order of the logs
> Fixed issue with logging indexing

- custom-commands/README.md
This is one of several changes to come.
> Update the custom-commands landing page doc following support of 3 demos

- clients/cpp-console/docs/RaspberryPi.md
* closes #109 and closes #110 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
*  Read https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant/blob/master/clients/cpp-console/docs/RaspberryPi.md
* Ubuntu 20.04 ARM32 is supported on RPI 3,4
* Raspbian is not supported
* Only ARM32 is supported
> Clarify what is supported on RPi

- custom-commands/automotive/skill/AutomotiveDemo.json
- custom-commands/hospitality/skill/HospitalityDemo.json
- custom-commands/inventory/skill/InventoryDemo.json
... and update Custom Command JSON files to support all keywords
Tested all keywords using WVAC.
> Add new "ok speaker" keyword model 

- clients/csharp-uwp/UWPVoiceAssistantSample/App.xaml.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/Package.appxmanifest
- clients/csharp-uwp/UWPVoiceAssistantSample/SignalDetectionHelper.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/UWPVoiceAssistantSample.csproj
- clients/csharp-uwp/UWPVoiceAssistantSampleTests/UWPVoiceAssistantSampleTests.csproj
* Update timestamps for kws performance logging
* Update Speech SDK to 1.12
[ ] Yes
[x] No
[ ] Bugfix
[ ] Feature
```
> Update KWS Performance timestamps

- clients/csharp-uwp/UWPVoiceAssistantSample/Assets/ActivationKeywords/KeywordConfigurationsInfo.txt
- clients/csharp-uwp/UWPVoiceAssistantSample/UWPVoiceAssistantSample.csproj
* Update KeywordConfigurations.txt file to allow users to switch between Computer and Contoso easily
[ ] Yes
[x] No
[ ] Bugfix
[ ] Feature
> update KeywordConfigurations.txt file

- clients/cpp-console/src/windows/cppSample.vcxproj
- clients/cpp-console/src/windows/packages.config
* Update Speech SDK version for windows solution to 1.12
[ ] Yes
[x] No
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: update nuget version
> update speech sdk version to 1.12

- azure-pipelines.yml
* Add publish artifact task for cpp console
[ ] Yes
[x] No
[ ] Bugfix
[x] Feature
> add publish artifact task to pipeline for cpp console

- azure-pipelines.yml
* Publish only .exe, .dll, and .pdb file
[ ] Yes
[x] No
[ ] Bugfix
[x] Feature
> publish only necessary files

- custom-commands/hospitality/azure-function/HospitalityApp/HospitalityDemo.cs
- custom-commands/hospitality/skill/HospitalityDemo.json
Update Hospitality to not to turn on lights that are already on, etc.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
> Update Hospitality to not to turn on lights that are already on, etc.

- custom-commands/scripts/deployAll.ps1
- custom-commands/scripts/deployContainerFiles.ps1
updated storage resource to check if the resource is created. Added validation to resource parameter
Closes #437 
Closes #321 
```
[ ] Yes
[ x] No
```
```
[ ] Bugfix
[ ] Feature
[x ] Refactoring (no functional changes, no api changes)
```
run the deployment script.
> Update Deployment scripts

- clients/cpp-console/docs/GGECSpeaker.md
- clients/cpp-console/docs/RaspberryPi.md
- clients/cpp-console/scripts/GGEC/buildGGEC.bat
- clients/cpp-console/scripts/linux/buildArm32Linux.sh
- clients/cpp-console/scripts/linux/buildArm32LinuxWithMAS.sh
- clients/cpp-console/scripts/linux/buildx64Linux.sh
checking if the binaries are there and skipping download if they are. Also made sure to remove SDK download folder after build and edited scripts to avoid copying the few files that would appear in the base directory.
Closes #398 
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[x ] Feature
[x ] Refactoring (no functional changes, no api changes)
```
```
cd [repo-name]
npm install
```
```
```
* ...
> skipping sdk download if not necessary

- clients/cpp-console/docs/RaspberryPi.md
* Close #456 by adding documentation for Raspberry Pi OS
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
Read the RaspberryPi.md overview
> Add comments on Raspberry Pi OS

- custom-commands/README.md
- custom-commands/automotive/azure-function/AutomotiveApp/AutomotiveDemo.cs
- custom-commands/automotive/skill/AutomotiveDemo.json
- custom-commands/hospitality/skill/HospitalityDemo.json
- custom-commands/inventory/azure-function/InventoryApp/InventoryDemo.cs
- custom-commands/inventory/skill/InventoryDemo.json
Remove redundant speech response in Inventory and Automotive CC portals.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[x] Feature
```
> Remove redundant speech response in Inventory and Automotive CC portals.

- clients/cpp-console/scripts/linux/buildArm32Linux.sh
- clients/cpp-console/scripts/linux/buildArmLinux.sh
MAS should not be defined in this script
```
[ ] Yes
[x ] No
```
```
[x ] Bugfix
[ ] Feature
```
run the script on a linux device
> Removed MAS macro from this script

- clients/cpp-console/include/DeviceStatusIndicators.h
- clients/cpp-console/include/DialogManager.h
- clients/cpp-console/src/common/DeviceStatusIndicators.cpp
- clients/cpp-console/src/common/DialogManager.cpp
- clients/cpp-console/src/common/Main.cpp
Add stop listening to CPP console
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
> Add stop listening to CPP console

- clients/cpp-console/include/DialogManager.h
- clients/cpp-console/src/common/DialogManager.cpp
- clients/cpp-console/src/common/Main.cpp
In DialogManager class add private ResumeKws, make private SetKeywordActivationState, PauseKws.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
> Add private ResumeKws, make private SetKeywordActivationState, PauseKws

- custom-commands/automotive/visualization/automotive.html
- custom-commands/inventory/visualization/inventory.html
I noticed that the tab title in the browser for the Inventory Demo is wrong. 
```
[ ] Yes
[x ] No
```
```
[x ] Bugfix
[ ] Feature
```
> Fix HTML titles in the demos

- clients/csharp-wpf/VoiceAssistantClient/MainWindow.xaml.cs
* Scroll to latest user and bot message in the conversation view
[ ] Yes
[x] No
[ ] Bugfix
[x] Feature
* Send text input,
* Send voice input
* Conversation view should scroll to the latest message from either Bot or User
> Scroll to newest message in Conversation View

- clients/csharp-wpf/VoiceAssistantClient/SettingsDialog.xaml
- clients/csharp-wpf/VoiceAssistantClient/SettingsDialog.xaml.cs
* HyperLink in Settings View to GitHub page
[ ] Yes
[x] No
[ ] Bugfix
[x] Feature
* Open Settings Page and click on "GitHub Page"
* [GitHub location](https://github.com/Azure-Samples/Cognitive-Services-Voice-Assistant/tree/master/clients/csharp-wpf)  should open in browser
> Add link to GitHub Page in Settings View

- clients/cpp-console/include/DeviceStatusIndicators.h
- clients/cpp-console/include/DialogManager.h
- clients/cpp-console/include/LinuxMicMuter.h
- clients/cpp-console/include/MicMuter.h
- clients/cpp-console/include/WindowsMicMuter.h
- clients/cpp-console/scripts/linux/buildArm32Docker.bat
- clients/cpp-console/scripts/linux/buildArm32Linux.sh
- clients/cpp-console/scripts/linux/buildArm32LinuxWithMAS.sh
- clients/cpp-console/scripts/linux/buildArmLinux.sh
- clients/cpp-console/scripts/linux/buildArmLinuxWithMAS.sh
- clients/cpp-console/scripts/linux/buildx64Linux.sh
- clients/cpp-console/src/common/DeviceStatusIndicators.cpp
- clients/cpp-console/src/common/DialogManager.cpp
- clients/cpp-console/src/common/Main.cpp
- clients/cpp-console/src/linux/LinuxMicMuter.cpp
- clients/cpp-console/src/windows/WindowsMicMuter.cpp
- clients/cpp-console/src/windows/cppSample.vcxproj
- clients/cpp-console/src/windows/cppSample.vcxproj.filters
1. Implement mute/unmute.
2. Add colorful text to highlight status and muted microphone.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
> mute and unmute

- custom-commands/demos/automotive/skill/AutomotiveDemo.json
- custom-commands/demos/hospitality/skill/HospitalityDemo.json
- custom-commands/demos/inventory/skill/InventoryDemo.json
- custom-commands/demos/scripts/deployCustomCommands.ps1
- custom-commands/scripts/bash/train-and-publish.sh
1.Update deployCustomCommands.ps1 to use CC API v1.0.
2. Update train-and-publish.sh to use Succeeded instead of Completed.
```
[Y] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe:
1. Update deployCustomCommands.ps1 to use CC API v1.0.
2. Update train-and-publish.sh to use Succeeded instead of Completed.
3. Need thorough test and merge to master after CC API v1.0 is released.
> Update deployCustomCommands.ps1 to use CC API v1.0.

- docs/CreateSampleVoiceAssistant.md
Minor typo
```
[ ] Yes
[ x] No
```
```
[ ] Bugfix
[ ] Feature
[ x ] Documentation content changes
```
> correcting a typo

- clients/cpp-console/docs/RaspberryPi.md
* Remove arm32 from the run script, closes #495 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
```
```
*export LD_LIBRARY_PATH="../lib/lib"
> running the sample should not specify arm32

- custom-commands/demos/README.md
- custom-commands/demos/automotive/README.md
- custom-commands/demos/careroom/README.md
- custom-commands/demos/hospitality/README.md
- custom-commands/demos/inventory/README.md
Some minor fixes to link and text in README.txt files
```
[ ] Yes
[x ] No
```
```
[ ] Bugfix
[ ] Feature
```
> Update links and text in README.txt files

- keyword-models/README.md
Update doc to seperate out the models that were created by hand vs the ones created from the portal. Also rename one of the model files.
```
[ ] Yes
[x ] No
```
> Minor updates related to keyword models

- custom-commands/demos/automotive/skill/AutomotiveDemo.json
- custom-commands/demos/careroom/skill/CareRoomDemo.json
- custom-commands/demos/hospitality/skill/HospitalityDemo.json
- custom-commands/demos/inventory/skill/InventoryDemo.json
- keyword-models/README.md
* Additional keywords for public use
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: Additional new keywords for public use
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Add new keywords

- custom-commands/demos/automotive/skill/AutomotiveDemo.json
- custom-commands/demos/careroom/README.md
- custom-commands/demos/careroom/skill/CareRoomDemo.json
- custom-commands/demos/hospitality/skill/HospitalityDemo.json
- custom-commands/demos/inventory/skill/InventoryDemo.json
- keyword-models/README.md
* Remove keywords xbox, hi nurse & raspberry pi
* Update the list of keywords in the custom command application, so they will be stripped out of recognized text
```
[ ] Yes
[x] No
```
> Remove keywords and update Custom Commands registered keywords

- clients/cpp-console/src/linux/LinuxAudioPlayer.cpp
Hi there, I hope this isn't too presumptuous of me!
I've been playing around with the C++ example and I fixed a wee snag I hit with audio playback on Linux, I thought it was worth raising my fix as a PR to stop anyone else getting stuck.
I was trying out the `cpp-console` example client on a Raspberry Pi 3 Model B+ (on Ubuntu Server Ubuntu 20.04.1 LTS for ARM 64 bit) and I hit a few snags with audio playback.
The first issue was with `m_shuttingDown` in `LinuxAudioPlayer` not being initialised to zero, it was starting with a nonsense value. I realise the header file initialises it to zero, but the compiler that comes with Ubuntu doesn't respect it (I'm not sure what ought to happen, I'm just reporting what does happen).
The second issue was that `PlayerThreadMain` in `LinuxAudioPlayer` …
> fix(cpp-console): fixing initialisation issues with LinuxAudioPlayer

- custom-commands/quick-start/SmartRoomLiteDemo.json
* Current dialog model is using an old version of the dialog model which is not longer compatible.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
* Download this file
* Create a new application in Custom Commands and import this file
* N/A
> Updating the format of JSON to v1

- clients/csharp-dotnet-core/voice-assistant-test-generator/DialogData.cs
- clients/csharp-dotnet-core/voice-assistant-test-generator/README.md
- clients/csharp-dotnet-core/voice-assistant-test-generator/TestFileGenerator.cs
- clients/csharp-dotnet-core/voice-assistant-test-generator/VoiceAssistantTestGenerator.csproj
- clients/csharp-dotnet-core/voice-assistant-test/tool/BotConnector.cs
- clients/csharp-dotnet-core/voice-assistant-test/tool/VoiceAssistantTest.csproj
* In the test generator, we specifiy and document an "ExpectedResponses" header to separate expected activity responses in generated test files. This adds extensibility in the future to support generating test files with multiple expected activities.
* In the test tool, a change is made to send silent audio to the input push stream, forcing segmentation in the service.  This fixes a bug pertaining to turning keyword off/on in different tests crashing the test tool.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[x] Feature
```
```
cd …
```
> Updates to generating and running voice assistant tests

- clients/csharp-dotnet-core/voice-assistant-test/README.md
- clients/csharp-dotnet-core/voice-assistant-test/docs/json-templates/app-config-template.json
- clients/csharp-dotnet-core/voice-assistant-test/tool/AppSettings.cs
- clients/csharp-dotnet-core/voice-assistant-test/tool/BotConnector.cs
Configuration for the bot connector sets properties for keyword verification according to configuration settings.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
*  Change app config settings
*  Also attempt without specifying "UseKeywordVerification" flag in app configuration.
*  Any provided tests should run appropriately.
> Include flag for keyword verification in application configuration.

- custom-commands/demos/automotive/README.md
- custom-commands/demos/careroom/README.md
- custom-commands/demos/hospitality/README.md
- custom-commands/demos/inventory/README.md
Some documentation links were broken after some files were moved.  This repairs those links.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Fix broken links in README files for Custom commands demos

- custom-commands/demos/hospitality/azure-function/HospitalityApp/HospitalityDemo.cs
- custom-commands/demos/hospitality/skill/en-us/HospitalityDemo.json
- custom-commands/demos/hospitality/visualization/hospitality.html
To demonstrate CC's functionality, we now generate the TTS response for commands within the CC interaction/completion rules, as opposed to in the Azure Function. This is done using both simple responses and lg templates.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
Make sure the Hospitality demo can still be deployed and function properly via the script/instructions.  No new hindrances should appear because of this change. The app should …
> Move TTS Response to Custom Commands App in Hospitality

- clients/csharp-wpf/VoiceAssistantClient/Properties/AssemblyInfo.cs
- clients/csharp-wpf/VoiceAssistantClient/VoiceAssistantClient.csproj
- clients/csharp-wpf/VoiceAssistantClient/packages.config
Update the VoiceAssistantClient (C#, wpf) to use Speech SDK 1.15 that was just released, instead of Speech SDK 1.14
> Update VoiceAssistantClient.exe to use SpeechSDK 1.15

- clients/csharp-uwp/UWPVoiceAssistantSample/AudioInput/AgentAudioInputProvider.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/AudioOutput/DialogAudioOutputAdapter.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/DialogManager.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/DirectLineSpeechDialogBackend.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/KeywordRegistration.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/Logging/LogRouter.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/MainPage.xaml
- clients/csharp-uwp/UWPVoiceAssistantSample/MainPage.xaml.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/Settings/LocalSettingsHelper.cs
1. Made hardware keyword spotter to work when EnableHardwareDetector is defined in config
2. Added EnableHypotheizedSpeech to local setting and bind to toggle
3. Fixed crash when release mode due to Logger
4. Fixed crash when connector is null
5. Fixed timespan to include keyword when signal verification is required
* Added hardware keyword spotter functionality. Fixed bugs
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
```
Test the app with …
```
> Enabled Hardware Keyword Spotter & fixed bugs

- clients/csharp-uwp/UWPVoiceAssistantSample/UWPVoiceAssistantSample.csproj
- clients/csharp-uwp/UWPVoiceAssistantSampleTests/UWPVoiceAssistantSampleTests.csproj
* ...
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: SDK update
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Update UWP sample to SDK v1.15.

- custom-commands/demos/automotive/skill/en-us/AutomotiveDemo.json
- custom-commands/demos/careroom/skill/en-us/CareRoomDemo.json
- custom-commands/demos/hospitality/skill/en-us/HospitalityDemo.json
As per discussion with the team, current interaction rules in CC demos are redundant: All interaction rules could be replaced with completion rules and required parameter. 
In this PR we will remove these useless interaction rules.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
> remove interactions rules in demos to make them easier to use

- clients/csharp-wpf/VoiceAssistantClient/Properties/AssemblyInfo.cs
- clients/csharp-wpf/VoiceAssistantClient/VoiceAssistantClient.csproj
- clients/csharp-wpf/VoiceAssistantClient/packages.config
> Update Windows Voice Assistant Client to version 1.16 (Uses Speech SDK version 1.16)

- custom-commands/demos/automotive/skill/en-us/AutomotiveDemo.json
- custom-commands/demos/careroom/skill/en-us/CareRoomDemo.json
- custom-commands/demos/hospitality/skill/en-us/HospitalityDemo.json
Reverts Azure-Samples/Cognitive-Services-Voice-Assistant#542 due to a bug in temperature
> Revert "remove interactions rules in demos to make them easier to use"

- clients/csharp-dotnet-core/voice-assistant-test/README.md
*  Hide comment
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
```
*  Preview the md
```
cd [repo-name]
npm install
```
```
```
Verify that the md change is valid. Only one line should be hidden
> Hide comments

- custom-commands/demos/careroom/skill/en-us/CareRoomDemo.json
- custom-commands/demos/careroom/test/CC_Text_TestInput/CC_Text_TestAdjustTemperature.json
- custom-commands/demos/careroom/test/CC_Text_TestInput/CC_Text_TestOpenClose.json
- custom-commands/demos/careroom/test/CC_Text_TestInput/CC_Text_TestTurnOnOff.json
- custom-commands/demos/hospitality/skill/en-us/HospitalityDemo.json
- custom-commands/demos/hospitality/test/CC_Text_TestInput/CC_Text_TestAdjustTemperature.json
- custom-commands/demos/hospitality/test/CC_Text_TestInput/CC_Text_TestFallbackCommand.json
- custom-commands/demos/hospitality/test/CC_Text_TestInput/CC_Text_TestGreetings.json
- custom-commands/demos/hospitality/test/CC_Text_TestInput/CC_Text_TestTurnOnOff.json
* Fix Hospitality/Careroom demo bugs and add more test cases
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
> Fix Hospitality/Careroom demo bugs and add more test cases

- custom-commands/demos/inventory/skill/en-us/InventoryDemo.json
- custom-commands/demos/inventory/test/CC_Text_TestInput/CC_Text_TestHelp.json
* Fix the issue that when order items, response will stuck at asking which item.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
*  Test from speech portal OR with Voice Assistant Test Tool
```
cd [repo-name]
npm install
```
```
```
> Fix inventory response stuck issue

- clients/csharp-wpf/JsonViewControl/JsonViewControl.csproj
- clients/csharp-wpf/JsonViewControl/packages.config
- clients/csharp-wpf/VoiceAssistantClient/Properties/AssemblyInfo.cs
- clients/csharp-wpf/VoiceAssistantClient/VoiceAssistantClient.csproj
- clients/csharp-wpf/VoiceAssistantClient/packages.config
Update Windows Voice Assistant Client to use Speech SDK 1.17 (also update some other Nugets)
> Update Windows Voice Assistant Client to use Speech SDK 1.17 (also update some other Nugets)

- custom-commands/demos/automotive/skill/en-us/AutomotiveDemo.json
- custom-commands/demos/automotive/test/CC_Text_TestInput/CC_Text_TestAdjustTemperature.json
- custom-commands/demos/automotive/test/CC_Text_TestInput/CC_Text_TestControlDefroster.json
- custom-commands/demos/automotive/test/CC_Text_TestInput/CC_Text_TestControlSeatWarmer.json
- custom-commands/demos/automotive/test/CC_Text_TestInput/CC_Text_TestHelp.json
- custom-commands/demos/automotive/test/CC_Text_TestInput/CC_Text_TestReset.json
* Fix automotive demo azure function, redeployed az and modifying tests
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
*  Test with Voice Assistant Test Tool
```
cd [repo-name]
npm install
```
```
```
> fix automotive demo az func and tests

- clients/csharp-uwp/README.md
- clients/csharp-uwp/UWPVoiceAssistantSample/AgentSessionWrapper.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/Assets/defaultConfig.json
- clients/csharp-uwp/UWPVoiceAssistantSample/IAgentSessionWrapper.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/IKeywordRegistration.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/KeywordRegistration.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/MainPage.xaml.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/Settings/AppSettings.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/Settings/LocalSettingsHelper.cs
- clients/csharp-uwp/UWPVoiceAssistantSample/UIAudioStatus.cs
- clients/csharp-uwp/UWPVoiceAssistantSampleTests/KeywordRegistrationTests.cs
- clients/csharp-uwp/UWPVoiceAssistantSampleTests/Mocks/MockKeywordRegistration.cs
- clients/csharp-uwp/UWPVoiceAssistantSampleTests/UnitTestApp.xaml.cs
* Add support for any combination of hardware and software based keyword spotter keyword detection
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
* if you want to test the hardware keyword spotter, you need a device that has hardware keyword spotter support
* Modify the configuration file with the desired combination of hardware keyword spotter (UseHardwareKeywordSpotter) and software keyword spotter (UseSoftwareKeywordSpotter) based keyword detection
```
cd [repo-name]
npm install
```
* Test …
> M hietala/hwkws swkws supported at the same time

- custom-commands/demos/scripts/deployCustomCommands.ps1
The import/export API for multi-language is v1.2-preview API and even though UI is using it, they are not release to public yet. Since all CC demos are single language now, update script to pick up single dialog model.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
Run script locally, the CC app is created and published.
./deployAll.ps1 -appName inventory -language en-us -resourceName InventoryDemo2 -region westus
```
> Update script to pick up dialog model from Json

- clients/cpp-console/docker/Dockerfile
- clients/cpp-console/docs/BuildForLinuxOnWindows.md
As the Speech SDK no longer supports end-of-life version 16.04
> Switch to mentioning Ubuntu 18.04 instead of 16.04

- clients/csharp-wpf/VoiceAssistantClient/Properties/AssemblyInfo.cs
- clients/csharp-wpf/VoiceAssistantClient/SettingsDialog.xaml
- clients/csharp-wpf/VoiceAssistantClient/VoiceAssistantClient.csproj
- clients/csharp-wpf/VoiceAssistantClient/packages.config
Also update SDK log file field name in the settings, as one customer got confused between app log (in the main page) and Speech SDK logs.
> Update Speech SDK version in Voice Assistant Client 

- custom-commands/quick-start/SmartRoomLiteDemo.json
Update the URL in start-up demo.
```
[ ] Yes
[ x] No
```
```
[ ] Bugfix
[ ] Feature
[ x] Documentation content changes
```
```
cd [repo-name]
npm install
```
```
```
* ...
> [Custom Commands] Fix webendpoint for demo
